version: '3'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    restart: unless-stopped
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    network_mode: host
  kafka:
    image: "confluentinc/cp-kafka:latest"
    restart: unless-stopped
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "127.0.0.1:32181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9093"
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 600000
      KAFKA_BROKER_ID: 1
    network_mode: host
