version: '3'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
    network_mode: host
  kafka:
    image: "confluentinc/cp-kafka:latest"
    restart: unless-stopped
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "127.0.0.1:32181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9093"
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 600000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    network_mode: host
